name: Build app and update Docker images

on:
  push:
   branches:
     - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: vars
        run: |
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          echo "::set-output name=docker_image_php::ghcr.io/netwerk-digitaal-erfgoed/datasets-php"
          echo "::set-output name=docker_image_nginx::ghcr.io/netwerk-digitaal-erfgoed/datasets-nginx"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.0.2

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Build and push Nginx image
        uses: docker/build-push-action@v2
        with:
          context: datasetdescriptions-demo-site/
          file: datasetdescriptions-demo-site/nginx/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_nginx }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_nginx }}:latest

      - name: Build and push PHP image
        uses: docker/build-push-action@v2
        with:
          context: datasetdescriptions-demo-site/
          file: datasetdescriptions-demo-site/php-fpm/Dockerfile
          push: true
          tags: |
            ${{ steps.vars.outputs.docker_image_php }}:${{ steps.vars.outputs.sha_short }}
            ${{ steps.vars.outputs.docker_image_php }}:latest

      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Store DigitalOcean credentials
        run: doctl kubernetes cluster kubeconfig save nde

      # See https://kubernetes.io/docs/concepts/workloads/controllers/deployment/#updating-a-deployment
      - name: Update deployment
        run: |
          kubectl set image deployment/datasets nginx=${{ steps.vars.outputs.docker_image_nginx }}:${{ steps.vars.outputs.sha_short }} --record
          kubectl set image deployment/datasets php=${{ steps.vars.outputs.docker_image_php }}:${{ steps.vars.outputs.sha_short }} --record

      - name: Verify deployment
        run: kubectl rollout status deployment/datasets
